// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env["DATABASE_URL"] ??
      (process.env["RAILWAY_VOLUME_MOUNT_PATH"]
        ? `file:${process.env["RAILWAY_VOLUME_MOUNT_PATH"].replace(/\/+$/, "")}/hospital.db`
        : "file:./hospital.db"),
  },
});
