export {
  acceptNextDoctorVisit,
  acceptNextLabItem,
  addAssignments,
  addPatientNote,
  buildSpecialtyCatalog,
  buildUnifiedAssignmentCatalog,
  checkoutPatient,
  completeDoctorVisit,
  createPatient,
  getHospitalSnapshot,
  getTestCatalog,
  getUnreadNotificationCount,
  getVisibleNotifications,
  markDoctorVisitNotHere,
  markLabItemNotHere,
  markLabItemResultsReady,
  markLabItemTaken,
  markLabResultsReady,
  markNotificationRead,
  normalizeBackendCode,
  prefetchPatientDetails,
  startDoctorVisit,
  startLabItem,
  subscribeToHospitalStream,
  updatePatientCore,
} from './hospitalRepository'
